# 1. Pricing the Callable Bond

In [1]:
#run this everytime an edit is made in utils.py so that we can use the helper functions in this Python Notebook
import importlib
import utils
importlib.reload(utils)

In [11]:
import pandas as pd
import numpy as np

#Loading in Callable Bond Info
callable_bonds_info = pd.read_excel("callable_bonds_2025-02-13.xlsx", sheet_name="info")
display(callable_bonds_info)

#Loading in the bond quotes
callable_bonds_quotes = pd.read_excel("callable_bonds_2025-02-13.xlsx", sheet_name="quotes")
display(callable_bonds_quotes)

#Loading in discount rate data
discount_curve = pd.read_excel("discount_curve_2025-02-13.xlsx")
display(discount_curve.head())

,info,FHLMC 0.97 01/28/28,FHLMC 1 1/4 01/29/30,FHLMC 4.41 01/28/30
0,CUSIP,3134GW5F9,3134GWGK6,3134HA4V2
1,Issuer,FREDDIE MAC,FREDDIE MAC,FREDDIE MAC
2,Maturity Type,CALLABLE,CALLABLE,CALLABLE
3,Issuer Industry,GOVT AGENCY,GOVT AGENCY,GOVT AGENCY
4,Amount Issued,30000000,25000000,10000000
5,Cpn Rate,0.0097,0.0125,0.0441
6,Cpn Freq,2,2,2
7,Date Quoted,2025-02-13 00:00:00,2025-02-13 00:00:00,2025-02-13 00:00:00
8,Date Issued,2020-10-28 00:00:00,2020-07-29 00:00:00,2025-01-28 00:00:00
9,Date Matures,2028-01-28 00:00:00,2030-01-29 00:00:00,2030-01-28 00:00:00
10,Date of First Possible Call,2021-01-28 00:00:00,2021-01-29 00:00:00,2028-01-28 00:00:00
11,Date Next Call,2025-04-28 00:00:00,2025-04-29 00:00:00,2028-01-28 00:00:00
12,Strike,100,100,100

,quotes,FHLMC 0.97 01/28/28,FHLMC 1 1/4 01/29/30,FHLMC 4.41 01/28/30
0,Date Quoted,2025-02-13 00:00:00,2025-02-13 00:00:00,2025-02-13 00:00:00
1,TTM,2.954141,4.958248,4.95551
2,Clean Price,90.144,85.1095,99.893
3,Dirty Price,90.187111,85.161583,100.089
4,Accrued Interest,0.043111,0.052083,0.196
5,YTM Call,54.240686,85.395782,4.448321
6,YTM Maturity,4.572927,4.646847,4.433845
7,Duration,2.917203,4.806058,4.496738
8,Modified Duration,2.851993,4.696929,4.399211
9,Convexity,0.095944,0.248027,0.227173
10,Treasury YLD Spread,25.1356,26.0091,4.7089
11,OAS Spread,25.829994,25.969759,-26.768085
12,Implied Vol,19.598991,21.093378,23.879829

   ttm maturity date  spot rate  discount
0  0.5    2025-08-13   0.043743  0.978597
1  1.0    2026-02-13   0.042890  0.958451
2  1.5    2026-08-13   0.042238  0.939228
3  2.0    2027-02-13   0.041843  0.920515
4  2.5    2027-08-13   0.041632  0.902117

# 1.1.
Use the discount curve data to price both the callable and reference bonds.

Also calculate the price of the hypothetical bonds, where we consider a non-callable version of the callable bond with

maturity unchanged

maturity at the call date.